### PR TITLE
YahooDinanceData fromdate, todate fix

### PR DESCRIPTION
**Pull request by happydasch**
YahooDinanceData fromdate, todate fix

both params are needed in request. added default values if dates not provided, fixed also wrong todate check

### CODE REVIEW

**Comment by neilsmurphy** [comment]
Are we saying that the user should be able to call the data for a backtest without any dates? Would it be preferable to make the user input dates?

**Comment by happydasch** [comment]
I tried to keep it close to other feeds which work without a fromdate but was also unsure about that. Usually what happens without fromdate is fetching latest data.

**Comment by neilsmurphy** [comment]
I like this and there was an error in the original code as well. I think this line can be simplified: 
```
else:
    # use a date far away for fromdate if not provided
    period1 = (date(1980, 1, 1) - posix).total_seconds()
```
to 
```
period1 = 0
```
No point calculating the integer difference to 1980. Just go back to posix, which when subtracting itself, would be zero.

**Comment by happydasch** [comment]
i will squash the commits but am having a problem with some data files.

**Review by neilsmurphy — CHANGES_REQUESTED** [review]
There were some data files added to the last commit, did you want these in there for some reason?

**Comment by happydasch** [comment]
I created a new pull request with just the files needed to be committed and closed this one. I have some issues with two data files being shown as modified when doing a clean git check out.

**Pull request closed without merging**
