### PR TITLE
Readme file and travis, replace previous pull request.

### PR DESCRIPTION
**Pull request by neilsmurphy**
Needed one more update to text in travis file taking out a testing comment.

### CODE REVIEW

**Comment by neilsmurphy** [comment]
I'm getting conflicting files and I'm not sure how to resolve it.

**Comment by vladisld** [comment]
You are not sure about the wording in the text, or about the related git/github related procedure?

**Comment by neilsmurphy** [comment]
> You are not sure about the wording in the text, or about the related git/github related procedure?

My github experience is limited to saving  my own files. Sorry, i'm just a bit stumped. I took out a comment that shouldn't have been in the travis file, and now I'm getting conflicts. When I go to resolve them the button to do so is inactive. Am I to do this at the terminal on my machine? There are warnings about hurting the master file. 

Appreciate the help, I'll get better at this part.

**Comment by vladisld** [comment]
you may try to resolve the conflicts directly using the web editor ( see here for help : https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github). 

Alternatively you may resolve the conflicts in your local terminal - like a regular merge conflicts and push the changes back  to your branch.  It will appear as yet another commit with resolved changes.

**Comment by neilsmurphy** [comment]
Ok, manage to fix the conflicts then get    "This page is out of date. Start over " 
When I start over then I'm in a continuous loop fixing the conflicts.  
Couldn't find a definitive solution online.

**Comment by vladisld** [comment]
Please try to resolve it locally.  

Assuming your have your changes in your fork under branch "readme_update" (just for example):

1. git checkout master
2. git pull origin master
3. git checkout readme_update
4. git merge master
5. <resolve conflicts>
6. git commit -a -m "conflicts resolved"
7. git push origin readme_update

If the "readme_update" was the same branch your were originally created the pull request from, the new commit should appear in the current pull request. This commit should be mergeable without conflicts.

Hope this will work

**Comment by vladisld** [comment]
Hi Neil,  do you want me to try to update the README.md ?

**Pull request closed without merging**
